Repository dwyl/phoenix-chat-example, pull requests merged in 2023-02, with the labels that each got.

#152 [PR] Upgrading to `Phoenix 1.7`
  .formatter.exs
  .gitignore
  README.md
  assets/css/app.css
  assets/js/app.js
  assets/tailwind.config.js
  assets/vendor/topbar.js
  auth.md
  config/config.exs
  config/dev.exs
  config/prod.exs
  config/prod.secret.exs
  config/runtime.exs
  config/test.exs
  coveralls.json
  lib/chat/application.ex
  lib/chat/release.ex
  lib/chat_web.ex
  lib/chat_web/channels/room_channel.ex
  lib/chat_web/channels/user_socket.ex
  lib/chat_web/components/core_components.ex
  lib/chat_web/components/layouts.ex
  lib/chat_web/components/layouts/app.html.heex
  lib/chat_web/components/layouts/root.html.heex
  lib/chat_web/controllers/error_html.ex
  lib/chat_web/controllers/error_json.ex
  lib/chat_web/controllers/page_controller.ex
  lib/chat_web/controllers/page_html.ex
  lib/chat_web/controllers/page_html/home.html.heex
  lib/chat_web/endpoint.ex
  lib/chat_web/gettext.ex
  lib/chat_web/router.ex
  lib/chat_web/telemetry.ex
  lib/chat_web/templates/layout/app.html.heex
  lib/chat_web/templates/layout/live.html.heex
  lib/chat_web/templates/layout/root.html.heex
  lib/chat_web/templates/page/index.html.heex
  lib/chat_web/views/error_helpers.ex
  lib/chat_web/views/error_view.ex
  lib/chat_web/views/layout_view.ex
  mix.exs
  mix.lock
  priv/gettext/en/LC_MESSAGES/errors.po
  priv/gettext/errors.pot
  priv/repo/migrations/20230203114114_create_messages.exs
  priv/static/favicon.ico
  priv/static/images/phoenix.png
  priv/static/robots.txt
  rel/overlays/bin/migrate
  rel/overlays/bin/migrate.bat
  rel/overlays/bin/server
  rel/overlays/bin/server.bat
  test/chat_web/channels/room_channel_test.exs
  test/chat_web/controllers/error_html_test.exs
  test/chat_web/controllers/error_json_test.exs
  test/chat_web/controllers/page_controller_test.exs
  test/chat_web/views/error_view_test.exs
  test/chat_web/views/layout_view_test.exs
  test/chat_web/views/page_view_test.exs
  test/support/conn_case.ex
Labels: T1h, chore, in-review

#155 Add back rel folder
  rel/overlays/bin/migrate
  rel/overlays/bin/migrate.bat
  rel/overlays/bin/server
  rel/overlays/bin/server.bat
Labels: awaiting-review

#156 Add Chat.Release file
  coveralls.json
  lib/chat/release.ex
Labels: awaiting-review

#157 PR: restore old migration file name: 20221012115654_create_messages.exs
  priv/repo/migrations/20221012115654_create_messages.exs
Labels: awaiting-review

#159 [PR] Fixing scrolling and UI footer sticky
  README.md
  assets/js/app.js
  lib/chat_web/components/layouts/root.html.heex
  lib/chat_web/controllers/page_html/home.html.heex
Labels: bug, awaiting-review

#165 [PR] Adding list of online `people`
  README.md
  assets/js/app.js
  assets/js/user_socket.js
  auth.md
  lib/chat/application.ex
  lib/chat_web/channels/room_channel.ex
  lib/chat_web/components/core_components.ex
  lib/chat_web/controllers/page_html.ex
  lib/chat_web/controllers/page_html/home.html.heex
  lib/chat_web/presence.ex
  lib/chat_web/telemetry.ex
  mix.exs
  presence.md
  test/chat_web/channels/room_channel_test.exs
  test/support/data_case.ex
Labels: enhancement, in-review
